project:
  type: website
  output-dir: docs

website:
  title: "Tails or Types?"
  description: "Un Approccio Dimensionale alle Condizioni del Neurosviluppo?"
  favicon: images/favicon.ico  
  navbar:
    logo: images/logo.png  
    left:
      - href: index.html
        text: "Home"
      - href: approccio-dimensionale.html
        text: "Approccio dimensionale"
      - href: prove-scientifiche.html
        text: "Prove scientifiche"
      - href: implicazioni-cliniche.html
        text: "Implicazioni cliniche"
      - href: metodi-analisi.html
        text: "Metodi di analisi"
      - href: PRIN22.html
        text: "PRIN22"
      - href: risorse-bibliografia.html
        text: "Risorse e bibliografia"

format:
  html:
    link-external-icon: true
    link-external-newwindow: true
    theme: cosmo
    toc: true
    toc-depth: 2
    number-sections: false
    code-fold: false
    lang: it
